### ISSUE TITLE
unable to import module email.message, error showing email is not a package

### ISSUE THREAD

**Issue by Boby900** [tomitokko/20-python-projects#15]
when I am running the code of email.sender  file its showing that email.message is not the module and code not working. 
**from email.message import EmailMessage
ModuleNotFoundError: No module named 'email.message'; 'email' is not a package**
Your suggestions will be highly appreciated.

**Comment by rewaj56** [comment]
@Boby900 Hey, a quick search on stackoverflow and I found this thread, hope it helps.

"I encountered the same problem just now. Finally, I found it's because I name the python file as 'email.py'. It works after changing its name"

"Don't use "email" in your .py file name or even in package name as well. This will cause confusion to the interpreter between user declared module and pre-defined modules"

**Comment by Boby900** [comment]
Thanks for your suggestion.

**Comment by rewaj56** [comment]
@Boby900 Did the above-mentioned suggestion work? or you found another work around?

**Comment by Boby900** [comment]
I am sorry, currently I am not working on these.
but I will do it in meantime.

**Comment by bhuvi7358** [comment]
i had a same problem
